# Cloud Build configuration for Bonde Studio Carbon BIM Agent
# Based on official Google Cloud Build documentation:
# https://docs.cloud.google.com/build/docs/configuring-builds/create-basic-configuration
# https://docs.cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
#
# This ensures dist/ files are built and uploaded to GCS for Cloud Run volume mount

steps:
  # Step 1: Build dist/ separately for GCS upload (happens before Docker build)
  - name: 'node:22-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm ci
        npm run build
        echo "dist/ folder created for GCS upload"

  # Step 2: Upload dist/ to GCS bucket (for Cloud Run volume mount)
  # This updates the bucket that Cloud Run's volume mount reads from
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'dist/'
      - 'gs://ai-studio-bucket-502666211902-us-west1/services/bonde-studio-carbon-bim-agent/version-14/compiled/'

  # Step 3: Build Docker image (Dockerfile will rebuild dist/, which is fine)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/gen-lang-client-0621585357/cloud-run-source-deploy/bimagent/bonde-studio-carbon-bim-agent:$COMMIT_SHA'
      - '-t'
      - 'us-west1-docker.pkg.dev/gen-lang-client-0621585357/cloud-run-source-deploy/bimagent/bonde-studio-carbon-bim-agent:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-west1-docker.pkg.dev/gen-lang-client-0621585357/cloud-run-source-deploy/bimagent/bonde-studio-carbon-bim-agent'

# Images to be pushed to registry (required by official docs)
images:
  - 'us-west1-docker.pkg.dev/gen-lang-client-0621585357/cloud-run-source-deploy/bimagent/bonde-studio-carbon-bim-agent:$COMMIT_SHA'
  - 'us-west1-docker.pkg.dev/gen-lang-client-0621585357/cloud-run-source-deploy/bimagent/bonde-studio-carbon-bim-agent:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout (20 minutes)
timeout: '1200s'
